# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\meat_curing_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MeatCuringChamberMW(object):
    def setupUi(self, MeatCuringChamberMW):
        MeatCuringChamberMW.setObjectName("MeatCuringChamberMW")
        MeatCuringChamberMW.setEnabled(True)
        MeatCuringChamberMW.resize(538, 337)
        MeatCuringChamberMW.setAutoFillBackground(False)
        MeatCuringChamberMW.setInputMethodHints(QtCore.Qt.ImhNone)
        MeatCuringChamberMW.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MeatCuringChamberMW.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MeatCuringChamberMW)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumberSetTmpVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberSetTmpVal.setGeometry(QtCore.QRect(210, 150, 121, 41))
        self.lcdNumberSetTmpVal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberSetTmpVal.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberSetTmpVal.setObjectName("lcdNumberSetTmpVal")
        self.lcdNumberSetHumVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberSetHumVal.setGeometry(QtCore.QRect(370, 150, 121, 41))
        self.lcdNumberSetHumVal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberSetHumVal.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberSetHumVal.setObjectName("lcdNumberSetHumVal")
        self.lcdNumberCurTmp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberCurTmp.setEnabled(True)
        self.lcdNumberCurTmp.setGeometry(QtCore.QRect(210, 60, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdNumberCurTmp.setPalette(palette)
        self.lcdNumberCurTmp.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lcdNumberCurTmp.setAutoFillBackground(False)
        self.lcdNumberCurTmp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberCurTmp.setSmallDecimalPoint(False)
        self.lcdNumberCurTmp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberCurTmp.setProperty("value", 19.0)
        self.lcdNumberCurTmp.setProperty("intValue", 19)
        self.lcdNumberCurTmp.setObjectName("lcdNumberCurTmp")
        self.lcdNumberCurHum = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberCurHum.setGeometry(QtCore.QRect(370, 60, 121, 41))
        self.lcdNumberCurHum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumberCurHum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberCurHum.setObjectName("lcdNumberCurHum")
        self.labelTmpNow = QtWidgets.QLabel(self.centralwidget)
        self.labelTmpNow.setGeometry(QtCore.QRect(210, 110, 121, 21))
        self.labelTmpNow.setObjectName("labelTmpNow")
        self.labelHumNow = QtWidgets.QLabel(self.centralwidget)
        self.labelHumNow.setGeometry(QtCore.QRect(370, 110, 121, 21))
        self.labelHumNow.setObjectName("labelHumNow")
        self.labelTmpSetVal = QtWidgets.QLabel(self.centralwidget)
        self.labelTmpSetVal.setGeometry(QtCore.QRect(210, 200, 121, 21))
        self.labelTmpSetVal.setObjectName("labelTmpSetVal")
        self.labelHumSetVal = QtWidgets.QLabel(self.centralwidget)
        self.labelHumSetVal.setGeometry(QtCore.QRect(370, 200, 121, 21))
        self.labelHumSetVal.setObjectName("labelHumSetVal")
        self.groupBoxTmpHumMonitor = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxTmpHumMonitor.setGeometry(QtCore.QRect(190, 40, 311, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        self.groupBoxTmpHumMonitor.setPalette(palette)
        self.groupBoxTmpHumMonitor.setObjectName("groupBoxTmpHumMonitor")
        self.checkBoxFreezer = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxFreezer.setGeometry(QtCore.QRect(40, 60, 70, 17))
        self.checkBoxFreezer.setObjectName("checkBoxFreezer")
        self.checkBoxHumidifier = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxHumidifier.setGeometry(QtCore.QRect(40, 80, 70, 17))
        self.checkBoxHumidifier.setObjectName("checkBoxHumidifier")
        self.checkBoxHeater = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxHeater.setGeometry(QtCore.QRect(40, 120, 81, 17))
        self.checkBoxHeater.setObjectName("checkBoxHeater")
        self.checkBoxInternalFan = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxInternalFan.setGeometry(QtCore.QRect(40, 140, 91, 21))
        self.checkBoxInternalFan.setObjectName("checkBoxInternalFan")
        self.checkBoxDevice7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxDevice7.setGeometry(QtCore.QRect(40, 180, 70, 17))
        self.checkBoxDevice7.setObjectName("checkBoxDevice7")
        self.checkBoxFreshAirFan = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxFreshAirFan.setGeometry(QtCore.QRect(40, 160, 81, 17))
        self.checkBoxFreshAirFan.setObjectName("checkBoxFreshAirFan")
        self.checkBoxDevice8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxDevice8.setGeometry(QtCore.QRect(40, 200, 70, 17))
        self.checkBoxDevice8.setObjectName("checkBoxDevice8")
        self.groupBoxDeviceControl = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDeviceControl.setGeometry(QtCore.QRect(20, 40, 151, 201))
        self.groupBoxDeviceControl.setCheckable(False)
        self.groupBoxDeviceControl.setObjectName("groupBoxDeviceControl")
        self.checkBoxDehumidifier = QtWidgets.QCheckBox(self.groupBoxDeviceControl)
        self.checkBoxDehumidifier.setGeometry(QtCore.QRect(20, 60, 91, 17))
        self.checkBoxDehumidifier.setObjectName("checkBoxDehumidifier")
        self.labelSetSetPointTmp = QtWidgets.QLabel(self.centralwidget)
        self.labelSetSetPointTmp.setGeometry(QtCore.QRect(20, 260, 81, 16))
        self.labelSetSetPointTmp.setObjectName("labelSetSetPointTmp")
        self.labelSetSetPointHum = QtWidgets.QLabel(self.centralwidget)
        self.labelSetSetPointHum.setGeometry(QtCore.QRect(180, 260, 61, 16))
        self.labelSetSetPointHum.setObjectName("labelSetSetPointHum")
        self.pushButtonSetSetpointApply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSetSetpointApply.setGeometry(QtCore.QRect(340, 260, 61, 23))
        self.pushButtonSetSetpointApply.setObjectName("pushButtonSetSetpointApply")
        self.doubleSpinBoxSetSetPointTmp = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxSetSetPointTmp.setGeometry(QtCore.QRect(110, 260, 62, 22))
        self.doubleSpinBoxSetSetPointTmp.setMaximum(1000.0)
        self.doubleSpinBoxSetSetPointTmp.setObjectName("doubleSpinBoxSetSetPointTmp")
        self.doubleSpinBoxSetSetPointHum = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxSetSetPointHum.setGeometry(QtCore.QRect(250, 260, 62, 22))
        self.doubleSpinBoxSetSetPointHum.setObjectName("doubleSpinBoxSetSetPointHum")
        self.pushButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(420, 260, 61, 23))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.labelConn = QtWidgets.QLabel(self.centralwidget)
        self.labelConn.setGeometry(QtCore.QRect(30, 10, 71, 16))
        self.labelConn.setObjectName("labelConn")
        self.labelDataLogStat = QtWidgets.QLabel(self.centralwidget)
        self.labelDataLogStat.setGeometry(QtCore.QRect(200, 10, 81, 16))
        self.labelDataLogStat.setObjectName("labelDataLogStat")
        self.labelConnVal = QtWidgets.QLabel(self.centralwidget)
        self.labelConnVal.setGeometry(QtCore.QRect(97, 10, 81, 16))
        self.labelConnVal.setObjectName("labelConnVal")
        self.labelDataLogStatVal = QtWidgets.QLabel(self.centralwidget)
        self.labelDataLogStatVal.setGeometry(QtCore.QRect(281, 12, 47, 13))
        self.labelDataLogStatVal.setObjectName("labelDataLogStatVal")
        self.groupBoxDeviceControl.raise_()
        self.groupBoxTmpHumMonitor.raise_()
        self.lcdNumberSetTmpVal.raise_()
        self.lcdNumberSetHumVal.raise_()
        self.lcdNumberCurTmp.raise_()
        self.lcdNumberCurHum.raise_()
        self.labelTmpNow.raise_()
        self.labelHumNow.raise_()
        self.labelTmpSetVal.raise_()
        self.labelHumSetVal.raise_()
        self.checkBoxFreezer.raise_()
        self.checkBoxHumidifier.raise_()
        self.checkBoxHeater.raise_()
        self.checkBoxInternalFan.raise_()
        self.checkBoxDevice7.raise_()
        self.checkBoxFreshAirFan.raise_()
        self.checkBoxDevice8.raise_()
        self.labelSetSetPointTmp.raise_()
        self.labelSetSetPointHum.raise_()
        self.pushButtonSetSetpointApply.raise_()
        self.doubleSpinBoxSetSetPointTmp.raise_()
        self.doubleSpinBoxSetSetPointHum.raise_()
        self.pushButtonExit.raise_()
        self.labelConn.raise_()
        self.labelDataLogStat.raise_()
        self.labelConnVal.raise_()
        self.labelDataLogStatVal.raise_()
        MeatCuringChamberMW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MeatCuringChamberMW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MeatCuringChamberMW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MeatCuringChamberMW)
        self.statusbar.setObjectName("statusbar")
        MeatCuringChamberMW.setStatusBar(self.statusbar)
        self.actionPref = QtWidgets.QAction(MeatCuringChamberMW)
        self.actionPref.setObjectName("actionPref")
        self.actionAbout = QtWidgets.QAction(MeatCuringChamberMW)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MeatCuringChamberMW)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionPref)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MeatCuringChamberMW)
        QtCore.QMetaObject.connectSlotsByName(MeatCuringChamberMW)

    def retranslateUi(self, MeatCuringChamberMW):
        _translate = QtCore.QCoreApplication.translate
        MeatCuringChamberMW.setWindowTitle(_translate("MeatCuringChamberMW", "MeatCuringChamber"))
        self.labelTmpNow.setText(_translate("MeatCuringChamberMW", "Current Temperature (C)"))
        self.labelHumNow.setText(_translate("MeatCuringChamberMW", "Current Humidity (RH)"))
        self.labelTmpSetVal.setText(_translate("MeatCuringChamberMW", "Temperature Set Point"))
        self.labelHumSetVal.setText(_translate("MeatCuringChamberMW", "Humidity Set Point"))
        self.groupBoxTmpHumMonitor.setTitle(_translate("MeatCuringChamberMW", "Temperature and Humidity monitor"))
        self.checkBoxFreezer.setText(_translate("MeatCuringChamberMW", "Freezer"))
        self.checkBoxHumidifier.setText(_translate("MeatCuringChamberMW", "Humidifier"))
        self.checkBoxHeater.setText(_translate("MeatCuringChamberMW", "Heater"))
        self.checkBoxInternalFan.setText(_translate("MeatCuringChamberMW", "Internal fan"))
        self.checkBoxDevice7.setText(_translate("MeatCuringChamberMW", "Device 7"))
        self.checkBoxFreshAirFan.setText(_translate("MeatCuringChamberMW", "Fresh air fan"))
        self.checkBoxDevice8.setText(_translate("MeatCuringChamberMW", "Device 8"))
        self.groupBoxDeviceControl.setTitle(_translate("MeatCuringChamberMW", "Device Control"))
        self.checkBoxDehumidifier.setText(_translate("MeatCuringChamberMW", "Dehumidifier"))
        self.labelSetSetPointTmp.setText(_translate("MeatCuringChamberMW", "Set Temperature"))
        self.labelSetSetPointHum.setText(_translate("MeatCuringChamberMW", "Set Humidity"))
        self.pushButtonSetSetpointApply.setText(_translate("MeatCuringChamberMW", "Apply"))
        self.pushButtonExit.setText(_translate("MeatCuringChamberMW", "Exit"))
        self.labelConn.setText(_translate("MeatCuringChamberMW", "Connectivity:"))
        self.labelDataLogStat.setText(_translate("MeatCuringChamberMW", "Data log status:"))
        self.labelConnVal.setText(_translate("MeatCuringChamberMW", "Not Connected"))
        self.labelDataLogStatVal.setText(_translate("MeatCuringChamberMW", "Disabled"))
        self.menuFile.setTitle(_translate("MeatCuringChamberMW", "File"))
        self.menuHelp.setTitle(_translate("MeatCuringChamberMW", "Help"))
        self.actionPref.setText(_translate("MeatCuringChamberMW", "Preference"))
        self.actionAbout.setText(_translate("MeatCuringChamberMW", "About"))
        self.actionQuit.setText(_translate("MeatCuringChamberMW", "Quit"))

